### ISSUE TITLE
NUCLEO_F401RE : Export to IAR compiler errors.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-blinky#11]
Steps to reproduce:
$> mbed export -i IAR -m NUCLEO_F401RE

Open the IAR workspace newly created in the project folder. The correct target and debugger are selected by default. Click on "Project" -> "download and debug". Errors generated at the end of compilation. Build log is attached here: (tip: for quick parsing through the logs, the errors occur in the 1st few lines.. HAL_CM4.S )

[Nucleo_F401RE_IAR_export_error.txt](https://github.com/ARMmbed/oob-mbed-os-example-blinky/files/514375/Nucleo_F401RE_IAR_export_error.txt)

**Comment by ashok-rao** [comment]
RC2, export to IAR and open the generated IAR workspace, application **fails with ST-LINK and CMSIS-DAP, passes with simulator.**

![blinky_nucleo_f401re_iar_st_link_error](https://cloud.githubusercontent.com/assets/17567812/19267108/d4d9c45c-8fa4-11e6-9d28-28e521f4b9dd.jpg)

![blinky_nucleo_f401re_iar_cmsis_dap_error](https://cloud.githubusercontent.com/assets/17567812/19267083/b1b823ec-8fa4-11e6-8e94-f9031bd7b65d.jpg)

**Comment by 0xc0170** [comment]
> RC2, export to IAR and open the generated IAR workspace, application fails with ST-LINK and CMSIS-DAP, passes with simulator.

Just to confirm, as I tested it yesterday. The project builds but the debug session fails, is that correct? I found out that simulator is selected, and for that target it should be ST-LINK.

**Comment by ashok-rao** [comment]
@0xc0170 , yes. the project builds fine. Debug session fails with both ST-LINK and CMSIS-DAP. Simulator is fine.

**Comment by sarahmarshy** [comment]
What version of IAR are you using?

**Comment by ashok-rao** [comment]
@sarahmarshy , On Windows 8.1 64-bit.
![iar_version](https://cloud.githubusercontent.com/assets/17567812/19341002/8700bada-9123-11e6-8d0f-2e12bcf022df.jpg)

**Comment by 0xc0170** [comment]
@ashok-rao Can you create a new issue. This one is for compiler errors, that was resolved in rc2.

To continue , we should have a look why it fails to debug. ST-Link is selected in the debugger settings, but JTAG is selected, so maybe that is the issue. Try to switch to SWD and debug? But please open a new issue for debugger configuration. thanks

**Comment by ashok-rao** [comment]
@0xc0170 . It is indeed the issue with ST-LINK + JTAG selected. Debug session can be started by selecting SWD with ST LINK. I will open a separate issue for the debugger configuration.

**Comment by ashok-rao** [comment]
https://github.com/ARMmbed/oob-mbed-os-example-blinky/issues/27  - New issue for debug config.
