### ISSUE TITLE
NUCLEO_F401RE : Export to make_armc5 generates error.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-blinky#12]
Steps to reproduce:
$> mbed export -i make_armc5 -m NUCLEO_F401RE
$> make clean
$> make

Build log here:
C:\Ashok\mbed_CLI\Nucleo_F401RE\oob-mbed-os-example-blinky>make clean
rmdir /S /Q ".build"

C:\Ashok\mbed_CLI\Nucleo_F401RE\oob-mbed-os-example-blinky>make
C:/Ashok/mbed_CLI/Nucleo_F401RE/oob-mbed-os-example-blinky/makefile:761: warning: overriding commands for target `.s.o'
C:/Ashok/mbed_CLI/Nucleo_F401RE/oob-mbed-os-example-blinky/makefile:756: warning: ignoring old commands for target `.s.o'
"Compile: main.cpp"
"Compile: AnalogIn.cpp"
"Compile: BusIn.cpp"
"Compile: BusInOut.cpp"
"Compile: BusOut.cpp"
"Compile: CAN.cpp"
"Compile: Ethernet.cpp"
"Compile: FileBase.cpp"
"Compile: FileLike.cpp"
"Compile: FilePath.cpp"
"Compile: FileSystemLike.cpp"
"Compile: I2C.cpp"

(snip)

"Compile: stm32f4xx_hal_tim_ex.c"
"Compile: stm32f4xx_hal_uart.c"
"Compile: stm32f4xx_hal_usart.c"
"Compile: stm32f4xx_hal_wwdg.c"
"Compile: stm32f4xx_ll_fmc.c"
"Compile: stm32f4xx_ll_fsmc.c"
"Compile: stm32f4xx_ll_sdmmc.c"
"Compile: stm32f4xx_ll_usb.c"
"../mbed-os/targets/cmsis/TARGET_STM/TARGET_STM32F4/stm32f4xx_ll_usb.c", line 786: Warning:  #3108-D: attribute "__packed__" does not apply here
"../mbed-os/targets/cmsis/TARGET_STM/TARGET_STM32F4/stm32f4xx_ll_usb.c", line 812: Warning:  #3108-D: attribute "__packed__" does not apply here
../mbed-os/targets/cmsis/TARGET_STM/TARGET_STM32F4/stm32f4xx_ll_usb.c: 2 warnings, 0 errors
"link: oob-mbed-os-example-blinky.elf"
Fatal error: L6007U: Could not recognize the format of file ../build/iar_arm/Obj/HAL_CM4.o.
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
make[1]: *** [oob-mbed-os-example-blinky.elf] Error 1
make: *** [all] Error 2

**Comment by 0xc0170** [comment]
I am closing this, retested again. Please reopen if a problem persists.
