### ISSUE TITLE
K64F: Export to uVision5 build error, target not created

### ISSUE THREAD

**Issue by steveogborne** [ARMmbed/oob-mbed-os-example-blinky#14]
Steps to reproduce:
$> mbed export -i uvision5 -m K64F

Open the *.uvprojx file generated in the project folder. Target and debugger are set properly by default. Click "rebuild". Compile success but fails while linking. Screenshot below.

![image](https://cloud.githubusercontent.com/assets/6011929/19276845/9f2edf9c-8fcf-11e6-8e6d-80bc0628d2c9.png)

Build log:
*** Using Compiler 'V5.06 update 3 (build 300)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'
Rebuild target 'mbed-os-example-blinky'
compiling HAL_CM.c...
compiling rt_Event.c...
compiling rt_Mailbox.c...
compiling rt_List.c...

(snip)

compiling x509write_crt.c...
compiling x509write_csr.c...
compiling x509_crt.c...
compiling xtea.c...
compiling mbed-utest-shim.cpp...
.\mbed-os\features\frameworks\greentea-client\greentea-client/greentea_serial.h(13): warning:  #1-D: last line of file ends without a newline
mbed-os\features\frameworks\utest\mbed-utest-shim.cpp: 1 warning, 0 errors
linking...
C:\Users\steogb01\AppData\Local\Temp\pc98-3(120): warning: L6312W: Empty Execution region description for region RW_IRAM1
C:\Users\steogb01\AppData\Local\Temp\pc98-3: error: L6047U: The size of this image (33668 bytes) exceeds the maximum allowed for this version of the linker
Finished: 0 information, 1 warning, 0 error and 1 fatal error messages.
".\build\uvision5\mbed-os-example-blinky.axf" - 1 Error(s), 43 Warning(s).
Target not created.
Build Time Elapsed:  00:02:20

**Comment by 0xc0170** [comment]
@steveogborne The error is that you are using limited version of uvision (assuming that's what is installed). Linker size limit is 32kB.

**Comment by steveogborne** [comment]
Ah ok. Yes, apparently we have ran out of keil licenses. Thanks
