### ISSUE TITLE
K64F: export to IAR does not build: errors

### ISSUE THREAD

**Issue by steveogborne** [ARMmbed/oob-mbed-os-example-blinky#15]
Steps to recreate:
$> mbed export -m K64F -i IAR

Opened project file in IAR workbench. Target set correctly.
Rebuild all

Build log:
Building configuration: mbed-os-example-blinky - mbed-os-example-blinky 
Updating build tree... 
 
0  file(s) deleted. 
Updating build tree... 
cmain.S 
HAL_CM4.S 
Error[438]: This instruction is not available in the selected cpu/core C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 192 
Error[438]: This instruction is not available in the selected cpu/core C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 213 
Error[438]: This instruction is not available in the selected cpu/core C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 278 
Error[438]: This instruction is not available in the selected cpu/core C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 298 
Error[50]: Undefined symbol:'S16' C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 192 
Error[50]: Undefined symbol:'S31' C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 192 
Warning[408]: Not recommended operand syntax. Duplicate the first register operand, or select option -j (alternative syntax). C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 92 
Warning[408]: Not recommended operand syntax. Duplicate the first register operand, or select option -j (alternative syntax). C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 110 
Warning[408]: Not recommended operand syntax. Duplicate the first register operand, or select option -j (alternative syntax). C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 114 
Warning[408]: Not recommended operand syntax. Duplicate the first register operand, or select option -j (alternative syntax). C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 131 
Warning[408]: Not recommended operand syntax. Duplicate the first register operand, or select option -j (alternative syntax). C:\Users\steogb01\mbed-os-example-blinky\mbed-os\rtos\rtx\TARGET_CORTEX_M\TARGET_RTOS_M4_M7\TOOLCHAIN_IAR\HAL_CM4.S 135 
Error while running Assembler 
startup_MK64F12.S 
SVC_Table.S 
aesni.c  
AnalogIn.cpp  
aes.c  
analogin_api.c  
analogout_api.c  
arc4.c  
asn1parse.c  

(snip)

version_features.c  
utest_types.cpp  
x509_create.c  
x509.c  
x509_crl.c  
x509_csr.c  
x509write_crt.c  
x509write_csr.c  
xtea.c  
x509_crt.c  
 
Total number of errors: 6 
Total number of warnings: 25

**Comment by 0xc0170** [comment]
We might need more information. I can't reproduce this.

IAR version on my machine - 7.70 

I believe this is due to changes in IAR , I had this problem before. The older IAR has different  FPU settings that are not compatible unfortunately :(

**Comment by steveogborne** [comment]
My IAR version was correct. The problem was that I was using the "mbed-os-example-blinky" repo rather than the "oob-mbed-os-example-blinky". It builds correctly now. I have filed a ticket to correct the instructions in the getting started guide
