### ISSUE TITLE
ARM_BEETLE_SOC make_armc5: fatal link error

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-blinky#17]
```
C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky>make
(snip)
"link: oob-mbed-os-example-blinky.elf"
Fatal error: L3921U: Option '-ltcg' not available with your license.
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
```

Step to reproduce

```
mbed export -m ARM_BEETLE_SOC -i make_armc5
make clean
make
```

Generated Makefile is attached:
[Makefile.zip](https://github.com/ARMmbed/oob-mbed-os-example-blinky/files/523436/Makefile.zip)

Note that I have no problem about -t ARM build for this target.

**Comment by theotherjimmy** [comment]
https://github.com/ARMmbed/mbed-os/pull/3061

**Comment by toyowata** [comment]
@theotherjimmy I still got same error below.

```
"link: oob-mbed-os-example-blinky.elf"
Fatal error: L3921U: Option '-ltcg' not available with your license.
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
```

Also, the https://github.com/ARMmbed/mbed-os/pull/3061 fix makes side effect, because I saw following incorrect list in the generated Makefile.

```
LIBRARIES := -ldio.0.0.1  -ldio_platform.0.0.1 
```
In case of archives for armcc toolchain, there is no ```lib``` for the prefix.

https://github.com/ARMmbed/mbed-os/tree/master/targets/TARGET_ARM_SSG/TARGET_BEETLE/TOOLCHAIN_ARM_STD

**Comment by 0xc0170** [comment]
> ``Fatal error: L3921U: Option '-ltcg' not available with your license.``

where is that option coming from, cant locate it in Makefile, and it's deprecated to be used for armcc linker..

**Comment by toyowata** [comment]
ARM linker 5 doesn't support ```-l``` option to set library archives as other toolchain. It wrongly handles ```-l{archive}``` syntax as ```-ltcg``` which had been deprecated and we got strange error.

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0474f/CHDHIEGF.html

Also, ```-L``` is not a correct option to specify library path, but ```---userlibpath``` should be used.

Generated Makefile by mbed-cli
```
LIBRARY_PATHS := -L.././mbed-os/targets/TARGET_ARM_SSG/TARGET_BEETLE/TOOLCHAIN_ARM_STD 
LIBRARIES := -ldio.0.0.1  -ldio_platform.0.0.1 
```

This should be...
```
LIBRARY_PATHS := --userlibpath .././mbed-os/targets/TARGET_ARM_SSG/TARGET_BEETLE/TOOLCHAIN_ARM_STD 
LIBRARIES := cordio.0.0.1.ar cordio_platform.0.0.1.ar
```

I manually modified the Makefile and confirmed it generated .elf and .bin file for target.

**Comment by 0xc0170** [comment]
@toyowata Thank you ,that explains the error. This leads to a proposal I had to handle librariers per toolchain because of this inconsistencies.

**Comment by MarceloSalazar** [comment]
Should be fixed. Please tests in RC4.

**Comment by toyowata** [comment]
Tested and confirmed the fix in RC4.
