### ISSUE TITLE
ARM_BEETLE_SOC make_iar: fatal link error 

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-blinky#20]
```
C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky>make
(snip)
"link: oob-mbed-os-example-blinky.elf"

   IAR ELF Linker V7.70.1.11437/W32 for ARM
   Copyright 2007-2016 IAR Systems AB.
Fatal error[Ms007]: could not open file "libbed-os/targets/TARGET_ARM_SSG/TARGE
          T_BEETLE/TOOLCHAIN_IAR/libcordio.0.0.1.a"
            Directories searched:
              C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\.bu
                      ild
              C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbe
                      d-os\targets\TARGET_ARM_SSG\TARGET_BEETLE\TOOLCHAIN_IAR
Fatal error detected, aborting.
```
Step to reproduce

```
mbed export -m ARM_BEETLE_SOC -i make_iar
make clean
make
```

Generated Makefile is attached:
[Makefile.zip](https://github.com/ARMmbed/oob-mbed-os-example-blinky/files/523497/Makefile.zip)

Note that I have no problem about -t IAR build for this target.

**Comment by 0xc0170** [comment]
I reproduced this locally. Looks to me that paths to the cordio library is wrong:

``libbed-os/targets/TARGET_ARM_SSG/TARGET_BEETLE/TOOLCHAIN_IAR/libcordio.0.0.1.a``. our gcc toolchain does [name:3] to the library thus the beginning is not correct as it already contains path.

cc @theotherjimmy @sarahmarshy

**Comment by theotherjimmy** [comment]
@0xc0170 Thanks for getting to the bottom of the issue. I have a quick fix for it PR coming soon.

**Comment by theotherjimmy** [comment]
@0xc0170  @toyowata see the linked PR.

**Comment by toyowata** [comment]
@theotherjimmy Thanks.  I locally modified the __init__.py for makefile and it now works fine.  e.g. exported make_iar build works.
