### ISSUE TITLE
README: Installing the wrong application in the instructions

### ISSUE THREAD

**Issue by steveogborne** [ARMmbed/oob-mbed-os-example-blinky#21]
The getting started guide instructions:

"
Get the example application!

From the command line, import the example:

mbed import mbed-os-example-blinky
cd mbed-os-example-blinky
"

Should this say: 
mbed import **oob**-mbed-os-example-blinky
cd **oob**-mbed-os-example-blinky
?

**Comment by 0xc0170** [comment]
Sorry about that. These examples are forked. It's not ideal, but I dont think we should change the readme, only fixing the code. 

We create patches that will be sent upstream (to the original repositories). Therefore I propose to close this and take this into the account.

**Comment by steveogborne** [comment]
Ok, whatever works for you. Should I close it or someone else?
