### ISSUE TITLE
README: Exporting uvision vs uvision5 and output not as predicted in instructions

### ISSUE THREAD

**Issue by steveogborne** [ARMmbed/oob-mbed-os-example-blinky#22]
https://github.com/ARMmbed/oob-mbed-os-example-blinky#export-the-project-to-keil-mdk-and-debug-your-application

Firstly should the line: 

mbed export -m K64F -i uvision

Instead be:

mbed export -m K64F - i uvision**5**

The original line does stuff but produces a whole load of errors and does not build. Output here if you're interested. 

[export to uvision.txt](https://github.com/ARMmbed/oob-mbed-os-example-blinky/files/524813/export.to.uvision.txt)

The uvision5 alternative exports fine but gives the following output:

C:\Users\steogb01\oob-mbed-os-example-blinky>mbed export -m K64F -i uvision5
c:\python27\lib\site-packages\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pur
e-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levensht
ein to remove this warning')
Scan: .
Scan: FEATURE_BLE
Scan: FEATURE_COMMON_PAL
Scan: FEATURE_LWIP
Scan: FEATURE_UVISOR
Scan: FEATURE_LOWPAN_BORDER_ROUTER
Scan: FEATURE_LOWPAN_HOST
Scan: FEATURE_LOWPAN_ROUTER
Scan: FEATURE_NANOSTACK
Scan: FEATURE_NANOSTACK_FULL
Scan: FEATURE_THREAD_BORDER_ROUTER
Scan: FEATURE_THREAD_END_DEVICE
Scan: FEATURE_THREAD_ROUTER
Scan: FEATURE_STORAGE

The instructions say:

You should see the following output:

Successful exports:
  * K64F::uvision       .\projectfiles\uvision_K64F\Unnamed_Project

I do not see this. I get the same output when exporting to IAR. I do not get the "successful exports" line. The exported application does work though

**Comment by 0xc0170** [comment]
I believe that output line was removed, and I dont see it anymore neither. Please, @sarahmarshy @theotherjimmy can you confirm? I might check sources if it was and we should update the Readme file.
