### ISSUE TITLE
nRF51_DK: Cannot start debug session in KEIL uVision5 after export from CLI.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-blinky#7]
Steps to reproduce:
1. $> mbed export -i uvision5 -m nrf51_dk
2. Open the uVision5 project generated in the example project folder.
3. Select target as "NRF51422_xxAC" under "options for target.." and "CMSIS-DAP" as debugger under "Debug" tab.
4. Rebuild all.
Leads to the following error. Full build log attached below.
![keil_export_error](https://cloud.githubusercontent.com/assets/17567812/19150736/688e9292-8bc0-11e6-81d0-b77407e453f7.jpg)

Full build log here:
[KEIL_build_log.txt](https://github.com/ARMmbed/oob-mbed-os-example-blinky/files/513590/KEIL_build_log.txt)

**Comment by 0xc0170** [comment]
This should be fixed with rc2, thus closing
