### ISSUE TITLE
nRF51_DK: make_armc5 export generates L6654E error.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-blinky#8]
Steps to reproduce:
$> mbed export -i make_armc5 -m nrf51_dk
$> make clean
$> make

Compiles fine, but generates linker error L6654E.

(snip)
"Compile: softdevice_handler.c"
"Compile: softdevice_handler_appsh.c"
"Compile: serial_api.c"
"Compile: sleep.c"
"Compile: spi_api.c"
"Compile: us_ticker.c"
"Assemble: startup_nRF51822.s"
"Compile: sys.cpp"
"Compile: cmsis_nvic.c"
"Compile: system_nrf51.c"
"link: oob-mbed-os-example-blinky.elf"
Error: L6654E: Rejected Local symbol .text13 referred to from non group member BLE.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text74 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text76 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text78 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text82 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text86 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text90 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text92 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text94 referred to from non group member btle.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text72 referred to from non group member btle_discovery.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text74 referred to from non group member btle_discovery.o(.iar.stackusage)

(snip)

Error: L6654E: Rejected Local symbol .text9 referred to from non group member equeue_mbed.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text11 referred to from non group member equeue_mbed.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text19 referred to from non group member equeue_mbed.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text9 referred to from non group member NetworkInterface.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text9 referred to from non group member NetworkStack.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text14 referred to from non group member nRF5xCharacteristicDescriptorDiscoverer.o(.iar.stackusage)

(snip)

Error: L6654E: Rejected Local symbol .debug_info159 referred to from non group member test_env.o(.iar.debug_line)
Error: L6654E: Rejected Local symbol .text23 referred to from non group member utest_harness.o(.iar.stackusage)
Error: L6654E: Rejected Local symbol .text33 referred to from non group member utest_shim.o(.iar.stackusage)
Finished: 0 information, 0 warning and 135 error messages.
make[1]: *** [oob-mbed-os-example-blinky.elf] Error 1
make: *** [all] Error 2

**Comment by ashok-rao** [comment]
RC2, issue fixed. But documentation needs to be updated with asking the user to burn the "-combined.hex" file to the target. There is currently no mention of this in the documentation.

**Comment by 0xc0170** [comment]
Resolve, the doc update is trackked in the issue number 9 thus closing this one
