### ISSUE TITLE
nRF51_DK: make_gcc_arm export produces link error.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/oob-mbed-os-example-blinky#9]
Steps to reproduce:
$> mbed export -i make_gcc_arm -m nrf51_dk
$> make clean
$> make

C:\Ashok\mbed_CLI\nRF51_OOB_example\oob-mbed-os-example-blinky>mbed export -i make_gcc_arm -m nrf51_dk
WARNING: MBED_ARM_PATH set as environment variable but doesn't exist
Scan: .
Scan: FEATURE_BLE
Scan: FEATURE_COMMON_PAL
Scan: FEATURE_LWIP
Scan: FEATURE_UVISOR
Scan: FEATURE_LOWPAN_BORDER_ROUTER
Scan: FEATURE_LOWPAN_HOST
Scan: FEATURE_LOWPAN_ROUTER
Scan: FEATURE_NANOSTACK
Scan: FEATURE_NANOSTACK_FULL
Scan: FEATURE_THREAD_BORDER_ROUTER
Scan: FEATURE_THREAD_END_DEVICE
Scan: FEATURE_THREAD_ROUTER
Scan: FEATURE_STORAGE

C:\Ashok\mbed_CLI\nRF51_OOB_example\oob-mbed-os-example-blinky>make clean
rmdir /S /Q ".build"

C:\Ashok\mbed_CLI\nRF51_OOB_example\oob-mbed-os-example-blinky>make
C:/Ashok/mbed_CLI/nRF51_OOB_example/oob-mbed-os-example-blinky/makefile:1127: warning: overriding commands for target `.s.o'
C:/Ashok/mbed_CLI/nRF51_OOB_example/oob-mbed-os-example-blinky/makefile:1122: warning: ignoring old commands for target `.s.o'
"Compile: main.cpp"
"Compile: AnalogIn.cpp"
"Compile: BusIn.cpp"
"Compile: BusInOut.cpp"
"Compile: BusOut.cpp"

(snip)

"Compile: softdevice_handler_appsh.c"
"Compile: serial_api.c"
"Compile: sleep.c"
"Compile: spi_api.c"
"Compile: us_ticker.c"
"Assemble: startup_NRF51822.s"
"Compile: cmsis_nvic.c"
"Compile: system_nrf51.c"
"link: oob-mbed-os-example-blinky.elf"
arm-none-eabi-gcc: error: CreateProcess: No such file or directory
make[1]: *** [oob-mbed-os-example-blinky.elf] Error 1
make: *** [all] Error 2

**Comment by ashok-rao** [comment]
RC2, issue fixed. But documentation needs to be updated with asking the user to burn the "-combined.hex" file to the target. There is currently no mention of this in the documentation.

**Comment by theotherjimmy** [comment]
>But documentation needs to be updated with asking the user to burn the "-combined.hex" file to the target. There is currently no mention of this in the documentation.

Good catch!

**Comment by ashok-rao** [comment]
Issue fixed with https://github.com/ARMmbed/oob-mbed-os-example-blinky/pull/30 . Closing. Thank you.
